=== ScilifelabDataCentre/RDM-guidelines/data-resources-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Data Resources Schema",
  "type": "object",
  "required": ["metadata_version", "last_updated", "data_types", "info_types", "areas", "items"],
  "properties": {
    "metadata_version": { "type": "string" },
    "last_updated": { "type": "string", "format": "date" },
    "study_types": { "type": "array", "items": { "type": "string" }, "uniqueItems": true },
    "data_types": { "type": "array", "items": { "type": "string" }, "uniqueItems": true },
    "info_types": { "type": "array", "items": { "type": "string" }, "uniqueItems": true },
    "areas": { "type": "array", "items": { "type": "string" }, "uniqueItems": true },
    "items": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["title", "short_title", "id", "related", "description", "url", "info_type", "area", "data_type"],
        "properties": {
          "title": { "type": "string" },
          "short_title": { "type": "string" },
          "id": { "type": "string" },
          "related": { "type": "array", "items": { "type": "string" } },
          "description": { "type": "string" },
          "file_extension": { "type": "string" },
          "url": { "type": "string", "format": "uri" },
          "submission_guidelines": { "type": "string", "format": "uri" },
          "info_type": {
            "type": "array",
            "items": { "enum": ["Repository", "Metadata standard", "Metadata format", "File format"] }
          },
          "keywords": { 
            "type": "array", 
            "items": { "type": "string" }, 
            "uniqueItems": true 
          },
          "area": { "type": "array", "items": { "type": "string" } },
          "study_type": { "type": "array", "items": { "type": "string" } },
          "data_type": { "type": "array", "items": { "type": "string" } }
        }
      }
    }
  }
}

=== ScilifelabDataCentre/RDM-guidelines/data/data-resources.json
{
  "$schema": "../data-resources-schema.json",
  "metadata_version": "5.0",
  "last_updated": "2026-05-27",
  "study_types": [
    "Genomics", "Metagenomics", "Transcriptomics", "Epigenomics",
    "Clinical Genomics","Population Genetics", 
    "Single-cell Transcriptomics", "Association Studies (GWAS)",
    "Structural Biology", "Proteomics", "Cryo-EM", "Mass Spectrometry",
    "Metabolomics", "Lipidomics", "NMR Spectroscopy",
    "Targeted Proteomics", "Single-cell Proteomics",
    "BioImaging", "Spatial Omics", "Tissue Imaging",
    "Multiomics", "Precision Medicine", "Statistical Genetics", "X-ray Crystallography"
  ],
  "data_types": ["Raw Reads", "Assemblies", "Single-cell RNA-seq",
    "Controlled Access Data", "Expression Matrices", "Count Tables", 
    "Genetic Variants", "Genotypes", "GWAS Summary Statistics", "Microarray Data", 
    "Density Maps", "Raw Images", "Bioimages",
    "3D Volume Maps", "Atomic Coordinates", "Protein Identifications",
    "Structure Factors", "Mass Spectra", "NMR Spectra", "Metabolite Profiles",
    "Experimental Metadata", "SRM/MRM Mass Spectra", "Peptide Identifications", 
    "Study descriptions", "Supplemental data", "Sample descriptions"
  ],
  "info_types": ["Repository", "Metadata standard", "Metadata format", "File format"],
  "areas": ["Cellular and Molecular Imaging", "Genomics", "Metabolomics and Exposomics", "Proteomics", "Spatial Omics", "Structural Biology"],
  "items": [
    {
      "title": "ENA (European Nucleotide Archive)",
      "short_title": "ENA",
      "id": "ena",
      "related": ["mixs","ena-checklists", "webin-cli", "fastq", "bam", "fasta", "embl"],
      "description": "",
      "url": "https://www.ebi.ac.uk/ena",
      "submission_guidelines": "https://ena-docs.readthedocs.io/en/latest/",
      "info_type": ["Repository"],
      "keywords": ["Raw Reads", "Assemblies", "Experimental Metadata","Genomics", "Metagenomics", "Spatial Omics"],
      "area": ["Genomics"],
      "study_type": ["Genomics", "Metagenomics", "Spatial Omics"],
      "data_type": ["Raw Reads", "Assemblies"]
    },
    {
      "title": "EGA (European Genome-phenome Archive)",
      "short_title": "EGA",
      "id": "ega",
      "related": ["fastq", "bam", "fasta", "vcf"],
      "description": "European Genome-phenome Archive (EGA) is a service for sharing personally identifiable [genetic](/topics/gdpr-ethical-review-glossary/#genetic-data) and phenotypic data resulting from biomedical research projects. The repository is hosted by the European Bioinformatics Institute (EMBL-EBI) and the Centre for Genomic Regulation (CRG). Any data submitted to the repository is subject to controlled access, which means that access to the data only will be granted after a formal application procedure.",
      "url": "https://ega-archive.org",
      "submission_guidelines": "https://ega-archive.org/submission/metadata/submission/sequencing-phenotype/submitter-portal/",
      "info_type": ["Repository"],
      "keywords": ["Genomics", "Clinical Genomics", "Precision Medicine"],
      "area": ["Genomics"],
      "study_type": ["Genomics", "Clinical Genomics", "Precision Medicine"],
      "data_type": ["Raw Reads", "Genotypes","Controlled Access Data"]
    },
    {
      "title": "FEGA (Federated European Genome-phenome Archive) Sweden",
      "short_title": "FEGA Sweden",
      "id": "fega",
      "related": ["fastq", "bam", "fasta", "vcf", "gwas-ssf"],
      "description": "FEGA Sweden is a repository for storing and sharing personally identifiable [genetic](/topics/gdpr-ethical-review-glossary/#genetic-data) and phenotypic data in Sweden in a way that meets the requirements of the [General Data Protection Regulation (GDPR)](/topics/gdpr-ethical-review-glossary/#gdpr-general-data-protection-regulation). It is part of the [Federated European Genome-phenome Archive](https://ega-archive.org/about/projects-and-funders/federated-ega/), which is a network consisting of several national nodes and the European Genome-phenome Archive (EGA). Researchers can create a submission request by filling in a form on the website.",
      "url": "https://fega.nbis.se",
      "submission_guidelines": "https://fega.nbis.se/submission/",
      "info_type": ["Repository"],
      "keywords": ["Genomics", "Clinical Genomics", "Precision Medicine"],
      "area": ["Genomics"],
      "study_type": ["Genomics", "Clinical Genomics", "Precision Medicine"],
      "data_type": ["Raw Reads", "Genotypes","Controlled Access Data"]
    },
    {
      "title": "ArrayExpress",
      "short_title": "ArrayExpress",
      "id": "arrayexpress",
      "related": ["miame", "fastq", "bam", "minseqe", "mage-tab", "cel"],
      "description": "ArrayExpress is suitable if you have microarray data, single-cell transcriptomics data, or other expression data. It is tightly integrated with ENA, any raw reads submitted to ArrayExpress will be put in ENA. ArrayExpress has its own submission portal, [Annotare](https://www.ebi.ac.uk/fg/annotare/login/), where information is available on what can be submitted and how.",
      "url": "https://www.ebi.ac.uk/biostudies/arrayexpress",
      "submission_guidelines": "https://www.ebi.ac.uk/fg/annotare/help/index.html",
      "info_type": ["Repository"],
      "keywords": ["Genomics","Transcriptomics", "Epigenomics", "Single-cell Transcriptomics", "Spatial Omics"],
      "area": ["Genomics"],
      "study_type": ["Genomics","Transcriptomics", "Epigenomics", "Single-cell Transcriptomics", "Spatial Omics"],
      "data_type": ["Expression Matrices", "Count Tables", "Raw Reads", "Single-cell RNA-seq", "Microarray Data"]
    },
    {
      "title": "EVA (European Variation Archive)",
      "short_title": "EVA",
      "id": "eva",
      "related": ["vcf", "fasta"],
      "description": "The home for all genetic variation data, including SNPs, indels, and structural variants across any species.",
      "url": "https://www.ebi.ac.uk/eva",
      "submission_guidelines": "https://www.ebi.ac.uk/eva/?Submit-Data",
      "info_type": ["Repository"],
      "keywords": ["Genomics","Population Genetics"],
      "area": ["Genomics"],
      "study_type": ["Genomics","Population Genetics"],
      "data_type": ["Genetic Variants", "Genotypes"]
    },
    {
      "title": "GWAS Catalog",
      "short_title": "GWAS",
      "id": "gwas",
      "related": ["gwas-ssf","vcf"],
      "description": "The standard source for curated and summary-level data from Genome-Wide Association Studies.",
      "url": "https://www.ebi.ac.uk/gwas",
      "submission_guidelines": "https://www.ebi.ac.uk/gwas/docs/submission",
      "info_type": ["Repository"],
      "keywords": ["Genomics","Association Studies (GWAS)", "Statistical Genetics"],
      "area": ["Genomics"],
      "study_type": ["Genomics","Association Studies (GWAS)", "Statistical Genetics"],
      "data_type": ["GWAS Summary Statistics"]
    },
    {
      "title": "MIxS (Minimum Information about any (x) Sequence)",
      "short_title": "MIxS",
      "id": "mixs",
      "related": ["ena"],
      "description": "Ensures metadata standards for environmental sequencing.",
      "url": "https://github.com/GenomicsStandardsConsortium/mixs",
      "info_type": ["Metadata standard"],
      "keywords": ["sample", "ENA","Genomics", "Metagenomics"],
      "area": ["Genomics"],
      "study_type": ["Genomics", "Metagenomics"],
      "data_type": ["Raw Reads", "Experimental Metadata"]
    },
    {
      "title": "MIAME (Minimum Information About a Microarray Experiment)",
      "short_title": "MIAME",
      "id": "miame",
      "related": ["arrayexpress"],
      "description": "Guidelines for microarray experiments.",
      "url": "https://www.fged.org/projects/miame",
      "info_type": ["Metadata standard"],
      "keywords": ["ArrayExpress","Transcriptomics", "Epigenomics"],
      "area": ["Genomics"],
      "study_type": ["Transcriptomics", "Epigenomics"],
      "data_type": ["Expression Matrices", "Count Tables", "Microarray Data", "Experimental Metadata"]
    },
    {
      "title": "MAGE-TAB (MicroArray Gene Expression Tabular)",
      "short_title": "MAGE-TAB",
      "id": "mage-tab",
      "related": ["arrayexpress"],
      "description": "Format for microarray transcriptomics metadata. It is a simple tab-delimited, spreadsheet-based metadata format used for annotating and communicating microarray data in a MIAME compliant fashion.",
      "url": "https://www.fged.org/projects/mage-tab/",
      "info_type": ["Metadata format"],
      "keywords": ["ArrayExpress","Transcriptomics", "Epigenomics"],
      "area": ["Genomics"],
      "study_type": ["Transcriptomics", "Epigenomics"],
      "data_type": ["Experimental Metadata", "Microarray Data", "Expression Matrices", "Count Tables"]
    },
    {
      "title": "MINSEQE (Minimum Information about a high throughput SEQuencing Experiment)",
      "short_title": "MINSEQE",
      "id": "minseqe",
      "related": ["arrayexpress"],
      "description": "Guidelines for high throughput sequencing experiment.",
      "url": "https://www.fged.org/projects/minseqe/",
      "info_type": ["Metadata standard"],
      "keywords": ["ArrayExpress","Transcriptomics", "Epigenomics","Single-cell Transcriptomics"],
      "area": ["Genomics"],
      "study_type": ["Transcriptomics", "Epigenomics","Single-cell Transcriptomics"],
      "data_type": ["Expression Matrices", "Count Tables", "Raw Reads","Single-cell RNA-seq", "Experimental Metadata"]
    },
    {
        "title": "ENA sample checklists",
        "short_title": "ENA checklists",
        "id": "ena-checklists",
        "related": ["ena","biosamples"],
        "description": "",
        "url": "https://www.ebi.ac.uk/ena/browser/checklists",
        "info_type": ["Metadata format"],
        "keywords": ["ENA", "BioSamples","Genomics", "Metagenomics", "Multiomics", "Spatial Omics"],
        "area": ["Genomics"],
        "study_type": ["Genomics", "Metagenomics", "Multiomics", "Spatial Omics"],
